# Generated by Django 5.2 on 2025-05-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_added_flag', models.CharField(default='N', max_length=1)),
                ('created', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notes for an exercise for reference later.', verbose_name='exercise notes')),
                ('created', models.DateTimeField(verbose_name='created date')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='order the sets were performed for each exercise.', verbose_name='set order')),
                ('weight_lbs', models.DecimalField(decimal_places=2, default=0, help_text='Enter weight in pounds, up to two decimal places.', max_digits=6, verbose_name='weight (lbs)')),
                ('reps', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('WU', 'Warm-Up'), ('WK', 'Working'), ('MX', 'Max'), ('MY', 'MyoRep'), ('DP', 'Drop')], default='WK', help_text='Select the set type (e.g., Warm-Up).', max_length=2, verbose_name='set type')),
                ('created', models.DateTimeField(verbose_name='ceated date')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_sets', to='api.exercise_hist')),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='workout name')),
                ('date', models.DateTimeField(verbose_name='workout date')),
                ('notes', models.TextField(blank=True, help_text='Notes for the workout for reference later.', verbose_name='workout notes')),
                ('created', models.DateTimeField(verbose_name='created date')),
                ('voided', models.CharField(default='N', max_length=1)),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workout_hist')),
            ],
        ),
        migrations.AddField(
            model_name='exercise_hist',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workout_hist'),
        ),
    ]
