# Generated by Django 5.2 on 2025-05-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise_hist',
            old_name='workout',
            new_name='workout_hist',
        ),
        migrations.RenameField(
            model_name='exset',
            old_name='exercise',
            new_name='exercise_hist',
        ),
    ]
