# Generated by Django 5.2 on 2025-05-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_workout_exercise_hist_workout_hist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='exercise_hist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='exset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ceated date'),
        ),
        migrations.AlterField(
            model_name='workout_hist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
    ]
