# Generated by Django 5.2 on 2025-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exercise_user_workout_hist_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout_hist',
            options={'verbose_name': 'Workout', 'verbose_name_plural': 'Workouts'},
        ),
        migrations.AddField(
            model_name='exset',
            name='target_reps',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='target reps'),
        ),
    ]
