# Generated by Django 5.2 on 2025-05-31 14:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_workout_hist_options_exset_target_reps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardio_Workout_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='workout name')),
                ('cardio_type', models.CharField(choices=[('RN', 'Run'), ('BK', 'Bike'), ('RW', 'Row'), ('MX', 'Mixed Cardio'), ('RK', 'Ruck'), ('SR', 'Stair Machine'), ('EL', 'Elliptical Machine'), ('OR', 'Other')], help_text='Select the type of cardio.', max_length=2, verbose_name='cardio type')),
                ('date', models.DateTimeField(verbose_name='workout date')),
                ('notes', models.TextField(blank=True, help_text='Notes for the workout for reference later.', verbose_name='workout notes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardio_workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run_Hist_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_mi', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Enter the distance in miles, up to two decimal places.', max_digits=6, verbose_name='distance (miles)')),
                ('cardio_workout_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.cardio_workout_hist')),
            ],
        ),
    ]
