# Generated by Django 5.2 on 2025-06-01 17:53

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cardio_workout_hist_run_hist_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardio_workout_hist',
            name='avg_hr_bpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='average heart rate (BPM)'),
        ),
        migrations.AddField(
            model_name='cardio_workout_hist',
            name='avg_power_w',
            field=models.IntegerField(blank=True, null=True, verbose_name='average power (W)'),
        ),
        migrations.AddField(
            model_name='cardio_workout_hist',
            name='cadance_per_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='cadence (per minute)'),
        ),
        migrations.AddField(
            model_name='cardio_workout_hist',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='calories burned'),
        ),
        migrations.AddField(
            model_name='cardio_workout_hist',
            name='distance_mi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Enter the distance in miles, up to two decimal places.', max_digits=6, verbose_name='distance (miles)'),
        ),
        migrations.AddField(
            model_name='cardio_workout_hist',
            name='duration',
            field=models.DurationField(default=datetime.timedelta, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='cardio_workout_hist',
            name='elevation_ft',
            field=models.IntegerField(blank=True, null=True, verbose_name='elevation (feet)'),
        ),
        migrations.AddField(
            model_name='cardio_workout_hist',
            name='outdoor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='outdoor indicator'),
        ),
        migrations.AlterField(
            model_name='cardio_workout_hist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardio_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Run_Hist_Details',
        ),
    ]
