# Generated by Django 5.2 on 2025-07-09 21:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_template_exercise_hist_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpl_ex_set',
            name='weight_lbs',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Enter weight in pounds, up to two decimal places.', max_digits=6, verbose_name='weight (lbs)'),
        ),
    ]
