# Generated by Django 5.2 on 2025-07-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ex_set_weight_lbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpl_workout_hist',
            name='user_added_flag',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
