# Generated by Django 5.2 on 2025-07-27 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tmpl_workout_hist_user_added_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmple_workout_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts_used', to='api.tmpl_workout_hist')),
                ('workout_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_used', to='api.workout_hist')),
            ],
        ),
    ]
