# Generated by Django 5.2 on 2025-07-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_template_hist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpl_workout_hist',
            name='user_added_flag',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
