# Generated by Django 5.2 on 2025-07-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_tmpl_workout_hist_user_added_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template_hist',
            old_name='tmple_workout_hist',
            new_name='tmpl_workout_hist',
        ),
    ]
