# Generated by Django 5.2 on 2025-07-30 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_tmple_workout_hist_template_hist_tmpl_workout_hist'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_hist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='created date'),
            preserve_default=False,
        ),
    ]
