# Generated by Django 5.2 on 2025-08-04 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_template_hist_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('name', models.TextField(blank=True, null=True)),
                ('template_ids_array', models.TextField(default='[]')),
                ('user_added_flag', models.CharField(default='N', max_length=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
