# Generated by Django 5.2 on 2025-08-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_template_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_folder',
            name='template_ids_array',
        ),
        migrations.AddField(
            model_name='template_folder',
            name='templates',
            field=models.ManyToManyField(blank=True, null=True, to='api.tmpl_workout_hist'),
        ),
    ]
