# Generated by Django 5.2 on 2025-08-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_template_folder_template_ids_array_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardio_workout_hist',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AddField(
            model_name='ex_set',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AddField(
            model_name='exercise_hist',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AddField(
            model_name='template_folder',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AddField(
            model_name='template_hist',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AddField(
            model_name='tmpl_ex_set',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AddField(
            model_name='tmpl_exercise_hist',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AddField(
            model_name='workout_hist',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
        migrations.AlterField(
            model_name='tmpl_workout_hist',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated date'),
        ),
    ]
