# Generated by Django 5.2 on 2025-07-05 12:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cardio_workout_hist_avg_hr_bpm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExSet',
            new_name='Ex_Set',
        ),
        migrations.CreateModel(
            name='Template_Exercise_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notes for an exercise for reference later.', verbose_name='exercise notes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Template_Ex_Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='order the sets were performed for each exercise.', verbose_name='set order')),
                ('weight_lbs', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Enter weight in pounds, up to two decimal places.', max_digits=6, verbose_name='weight (lbs)')),
                ('reps', models.PositiveSmallIntegerField()),
                ('target_reps', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='target reps')),
                ('type', models.CharField(choices=[('WU', 'Warm-Up'), ('WK', 'Working'), ('MX', 'Max'), ('MY', 'MyoRep'), ('DP', 'Drop')], default='WK', help_text='Select the set type (e.g., Warm-Up).', max_length=2, verbose_name='set type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ceated date')),
                ('template_exercise_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_ex_sets', to='api.template_exercise_hist')),
            ],
        ),
        migrations.CreateModel(
            name='Teomplate_Workout_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='workout name')),
                ('notes', models.TextField(blank=True, help_text='Notes for the workout for reference later.', verbose_name='workout notes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated date')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout_Template',
                'verbose_name_plural': 'Workout_Templates',
            },
        ),
        migrations.AddField(
            model_name='template_exercise_hist',
            name='template_workout_hist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_exercises', to='api.teomplate_workout_hist'),
        ),
    ]
