# Generated by Django 5.2 on 2025-07-05 20:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_exset_ex_set_template_exercise_hist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_exercise_hist',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='template_exercise_hist',
            name='template_workout_hist',
        ),
        migrations.RenameModel(
            old_name='Teomplate_Workout_Hist',
            new_name='Tmpl_Workout_Hist',
        ),
        migrations.CreateModel(
            name='Tmpl_Exercise_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notes for an exercise for reference later.', verbose_name='exercise notes')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise')),
                ('tmpl_workout_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmpl_exercises', to='api.tmpl_workout_hist')),
            ],
        ),
        migrations.CreateModel(
            name='Tmpl_Ex_Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='order the sets were performed for each exercise.', verbose_name='set order')),
                ('weight_lbs', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Enter weight in pounds, up to two decimal places.', max_digits=6, verbose_name='weight (lbs)')),
                ('reps', models.PositiveSmallIntegerField()),
                ('target_reps', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='target reps')),
                ('type', models.CharField(choices=[('WU', 'Warm-Up'), ('WK', 'Working'), ('MX', 'Max'), ('MY', 'MyoRep'), ('DP', 'Drop')], default='WK', help_text='Select the set type (e.g., Warm-Up).', max_length=2, verbose_name='set type')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ceated date')),
                ('tmpl_exercise_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmpl_ex_sets', to='api.tmpl_exercise_hist')),
            ],
        ),
        migrations.DeleteModel(
            name='Template_Ex_Set',
        ),
        migrations.DeleteModel(
            name='Template_Exercise_Hist',
        ),
    ]
